apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: { { .Values.service.type } }
  selector:
    app: myapp
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
      nodePort: 30001 # optional: fixed NodePort for local testing
