name: CI-CD with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest app/

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          container-runtime: docker

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy using Helm
        run: |
          # Added ./ to clarify this is a local folder path
          helm upgrade --install myapp ./helm/myapp

          # This helper command waits for the pods to be ready so you can see success in your logs
          kubectl rollout status deployment/myapp --timeout=90s

          # Finally, show the status of all resources
          kubectl get all
